import Link from "next/link";
import { redirect } from "next/navigation";
import { createSupabaseServerClient } from "@/lib/supabase/server";

export default async function AdminPage() {
  const supabase = await createSupabaseServerClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) redirect("/login");
  const { data: profile } = await supabase.from("profiles").select("role").eq("id", user.id).maybeSingle();
  if (profile?.role !== "admin") redirect("/dashboard");

  const { data: opportunities } = await supabase.from("content_opportunities").select("*").order("search_count", { ascending: false }).limit(10);
  const totalSearches = (opportunities ?? []).reduce((sum, x) => sum + (x.search_count ?? 0), 0);
  const articleGaps = (opportunities ?? []).filter(x => x.opportunity_type === "article").length;
  const productSignals = (opportunities ?? []).filter(x => x.opportunity_type === "product").length;
  const openSignals = (opportunities ?? []).filter(x => x.status === "open").length;

  return <main className="min-h-screen bg-[#f5f7f2] text-[#17351f]"><header className="border-b bg-white"><div className="mx-auto flex max-w-7xl items-center justify-between px-6 py-4"><div><Link href="/" className="text-2xl font-black">AGRIVA<span className="text-[#b58b28]">.</span></Link><span className="ml-3 rounded-full bg-[#17351f] px-3 py-1 text-xs font-bold text-white">ADMIN AI</span></div><Link href="/dashboard" className="text-sm font-bold text-[#1f7a45]">← User dashboard</Link></div></header><section className="mx-auto max-w-7xl px-6 py-10"><p className="text-sm font-bold uppercase tracking-[0.18em] text-[#b58b28]">AI Command Center</p><h1 className="mt-2 text-4xl font-black">Demand intelligence</h1><p className="mt-3 max-w-2xl text-[#617064]">Live signals from AGRIVA search activity for content and marketplace planning.</p><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[[totalSearches,"Tracked searches"],[articleGaps,"Article signals"],[productSignals,"Product signals"],[openSignals,"Open alerts"]].map(([v,l])=><div key={l} className="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-black/5"><p className="text-3xl font-black">{v}</p><p className="mt-2 text-sm text-[#657467]">{l}</p></div>)}</div><section className="mt-8 overflow-hidden rounded-3xl bg-white shadow-sm ring-1 ring-black/5"><div className="flex items-center justify-between border-b p-6"><div><h2 className="text-xl font-bold">Trending opportunities</h2><p className="mt-1 text-sm text-[#68786b]">Highest observed search demand</p></div><Link href="/admin/opportunities" className="rounded-xl bg-[#17351f] px-4 py-2 text-sm font-bold text-white">View all</Link></div>{(opportunities ?? []).map(row=><div key={row.id} className="grid gap-3 border-b p-5 md:grid-cols-[1.7fr_.6fr_.6fr_1fr]"><div><p className="font-bold">{row.keyword}</p><p className="mt-1 text-xs text-[#78867b]">{row.intent ?? "information"}</p></div><span className="text-sm font-black">{row.search_count}</span><span className="rounded-full bg-[#eef5ed] px-3 py-1 text-xs font-bold">{row.opportunity_type}</span><span className="text-sm text-[#647468]">{row.status}</span></div>)}{!opportunities?.length&&<p className="p-8 text-sm text-[#647468]">No demand signals yet.</p>}</section><div className="mt-8 grid gap-6 lg:grid-cols-3">{[["✍️","AI Content Studio","Turn high-demand topics into article briefs, FAQs and SEO drafts."],["🛒","Product Opportunities","Find search clusters showing product intent."],["🔔","Alert Rules","Set thresholds for demand and search growth."]].map(([icon,title,text])=><div key={title} className="rounded-3xl bg-[#e7f0e6] p-6"><span className="text-3xl">{icon}</span><h3 className="mt-5 text-lg font-bold">{title}</h3><p className="mt-2 text-sm leading-6 text-[#617064]">{text}</p><button className="mt-5 text-sm font-bold text-[#1f7a45]">Open module →</button></div>)}</div></section></main>;
}
