"use client";
import { useMemo, useState } from "react";

type Query={query:string;count:number;intent:string;priority:string};
const seed:Query[]=[{query:"ধানের পাতায় হলুদ দাগ কেন",count:28,intent:"Informational / Problem",priority:"High"},{query:"বাংলাদেশে ইউরিয়া সারের দাম",count:19,intent:"Product / Price",priority:"High"},{query:"আলু চাষের সময়",count:14,intent:"Informational",priority:"Medium"}];
export default function AISearchIntelligence(){const [queries,setQueries]=useState(seed);const [input,setInput]=useState("");const [brief,setBrief]=useState<{title:string;keyword:string;intent:string;outline:string[]}|null>(null);const [status,setStatus]=useState("Draft workflow ready");
 const sorted=useMemo(()=>[...queries].sort((a,b)=>b.count-a.count),[queries]);
 function classify(q:string){const s=q.toLowerCase();if(/price|দাম|কিনব|কিনতে|buy|cost/.test(s))return "Product / Price";if(/রোগ|পোকা|হলুদ|দাগ|কেন|how|why|কীভাবে|সমাধান/.test(s))return "Informational / Problem";return "Informational"}
 function add(){if(!input.trim())return;const i=queries.findIndex(x=>x.query.toLowerCase()===input.trim().toLowerCase());if(i>=0){const next=[...queries];next[i]={...next[i],count:next[i].count+1};setQueries(next)}else setQueries([{query:input.trim(),count:1,intent:classify(input),priority:"New"},...queries]);setInput("")}
 function makeBrief(q:Query){const title=q.intent.includes("Product")?`${q.query}: কৃষকের জন্য দাম ও কেনার গাইড`:`${q.query} — কৃষকের জন্য বিস্তারিত গাইড`;setBrief({title,keyword:q.query,intent:q.intent,outline:["Search intent and farmer problem","Verified facts and local context","Practical step-by-step guidance","Relevant AGRIVA tool or product links","FAQ and related questions"]});setStatus("Draft generated — admin review required")}
 return <section className="mt-8 grid gap-6 lg:grid-cols-[1.15fr_.85fr]"><div className="rounded-3xl bg-white p-6 shadow-sm"><div className="flex items-end justify-between gap-4"><div><h2 className="text-xl font-black">Search query alerts</h2><p className="mt-1 text-sm text-[#647468]">Prototype analytics for admin content discovery.</p></div><span className="rounded-full bg-[#eef5ed] px-3 py-1 text-xs font-bold">{queries.length} queries</span></div><div className="mt-5 flex gap-2"><input value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>e.key==="Enter"&&add()} placeholder="Add a farmer search query…" className="min-w-0 flex-1 rounded-xl border px-4 py-3"/><button onClick={add} className="rounded-xl bg-[#17351f] px-5 py-3 font-bold text-white">Add</button></div><div className="mt-6 space-y-3">{sorted.map((q,i)=><div key={`${q.query}-${i}`} className="rounded-2xl border p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-bold">{q.query}</p><p className="mt-1 text-xs text-[#647468]">{q.intent} · {q.count} searches · {q.priority}</p></div><button onClick={()=>makeBrief(q)} className="rounded-lg border px-3 py-2 text-xs font-bold">Create article brief</button></div></div>)}</div></div><div className="rounded-3xl bg-[#17351f] p-6 text-white"><p className="text-xs font-bold uppercase tracking-wider text-white/50">Admin content workflow</p><h2 className="mt-2 text-2xl font-black">{brief?"Article draft brief":"Select a query"}</h2>{brief?<><p className="mt-5 text-lg font-bold">{brief.title}</p><div className="mt-4 space-y-2 text-sm text-white/75"><p><b>Primary keyword:</b> {brief.keyword}</p><p><b>Intent:</b> {brief.intent}</p></div><h3 className="mt-6 font-black">Suggested outline</h3><ol className="mt-3 list-decimal space-y-2 pl-5 text-sm text-white/75">{brief.outline.map(x=><li key={x}>{x}</li>)}</ol><button onClick={()=>setStatus("Saved as draft — not published")} className="mt-6 w-full rounded-xl bg-white px-5 py-3 font-bold text-[#17351f]">Save as Draft</button></>:<p className="mt-5 text-sm leading-6 text-white/65">Choose a search query to generate an SEO-focused article brief. Publishing remains a manual admin action.</p>}<p className="mt-6 text-xs text-white/45">Status: {status}</p></div></section>}
