"use client";
import { useMemo, useState } from "react";

export default function CropProfitCalculator() {
  const [area, setArea] = useState("1"); const [cost, setCost] = useState("30000"); const [yieldQty, setYieldQty] = useState("2500"); const [price, setPrice] = useState("35");
  const result = useMemo(() => { const a=Number(area)||0,c=Number(cost)||0,y=Number(yieldQty)||0,p=Number(price)||0; const totalCost=c*a, revenue=y*a*p; return { totalCost, revenue, profit: revenue-totalCost, margin: revenue ? ((revenue-totalCost)/revenue)*100 : 0 }; }, [area,cost,yieldQty,price]);
  const input=(label:string,value:string,set:(v:string)=>void,unit:string)=><label className="block"><span className="text-sm font-bold">{label}</span><div className="mt-2 flex rounded-xl border bg-white"><input type="number" min="0" value={value} onChange={e=>set(e.target.value)} className="w-full rounded-xl px-4 py-3 outline-none"/><span className="px-4 py-3 text-sm text-[#78867b]">{unit}</span></div></label>;
  return <section className="mt-10 rounded-3xl bg-white p-7 shadow-sm"><h2 className="text-2xl font-black">Calculate your estimated crop profit</h2><div className="mt-6 grid gap-5 md:grid-cols-2">{input("Land area",""+area,setArea,"acre")}{input("Cost per acre",""+cost,setCost,"৳")}{input("Expected yield per acre",""+yieldQty,setYieldQty,"kg")}{input("Expected selling price",""+price,setPrice,"৳/kg")}</div><div className="mt-7 grid gap-4 sm:grid-cols-3"><div className="rounded-2xl bg-[#f5f7f2] p-5"><p className="text-sm text-[#647468]">Estimated cost</p><p className="mt-1 text-2xl font-black">৳{result.totalCost.toLocaleString()}</p></div><div className="rounded-2xl bg-[#f5f7f2] p-5"><p className="text-sm text-[#647468]">Estimated revenue</p><p className="mt-1 text-2xl font-black">৳{result.revenue.toLocaleString()}</p></div><div className="rounded-2xl bg-[#eef5ed] p-5"><p className="text-sm text-[#647468]">Estimated profit</p><p className="mt-1 text-2xl font-black">৳{result.profit.toLocaleString()}</p><p className="mt-1 text-xs text-[#647468]">Margin {result.margin.toFixed(1)}%</p></div></div></section>;
}
