"use client";
import { useEffect, useState } from "react";

type Weather = { current?: { temperature_2m:number; relative_humidity_2m:number; precipitation:number; wind_speed_10m:number }; daily?: { time:string[]; temperature_2m_max:number[]; temperature_2m_min:number[]; precipitation_probability_max:number[]; precipitation_sum:number[] } };
export default function FarmWeather(){
 const [lat,setLat]=useState("23.8103"); const [lon,setLon]=useState("90.4125"); const [data,setData]=useState<Weather|null>(null); const [loading,setLoading]=useState(false); const [error,setError]=useState("");
 async function load(a=lat,b=lon){setLoading(true);setError("");try{const u=new URL("https://api.open-meteo.com/v1/forecast");u.searchParams.set("latitude",a);u.searchParams.set("longitude",b);u.searchParams.set("current","temperature_2m,relative_humidity_2m,precipitation,wind_speed_10m");u.searchParams.set("daily","temperature_2m_max,temperature_2m_min,precipitation_probability_max,precipitation_sum");u.searchParams.set("timezone","auto");u.searchParams.set("forecast_days","7");const r=await fetch(u);if(!r.ok)throw new Error("Weather request failed");setData(await r.json());}catch(e){setError("Weather data could not be loaded. Check the coordinates or try again.");}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 function locate(){if(!navigator.geolocation){setError("Location is not supported by this browser.");return}navigator.geolocation.getCurrentPosition(p=>{const a=p.coords.latitude.toFixed(4),b=p.coords.longitude.toFixed(4);setLat(a);setLon(b);load(a,b)},()=>setError("Location permission was not granted. You can enter coordinates manually."))}
 return <section className="mt-8 rounded-3xl bg-white p-6 shadow-sm"><div className="grid gap-4 md:grid-cols-[1fr_1fr_auto_auto]"><label className="text-sm font-bold">Latitude<input value={lat} onChange={e=>setLat(e.target.value)} className="mt-2 w-full rounded-xl border px-4 py-3 font-normal"/></label><label className="text-sm font-bold">Longitude<input value={lon} onChange={e=>setLon(e.target.value)} className="mt-2 w-full rounded-xl border px-4 py-3 font-normal"/></label><button onClick={()=>load()} className="self-end rounded-xl bg-[#17351f] px-5 py-3 font-bold text-white">{loading?"Loading…":"Get forecast"}</button><button onClick={locate} className="self-end rounded-xl border px-5 py-3 font-bold">Use my location</button></div>{error&&<p className="mt-4 rounded-xl bg-red-50 p-4 text-sm text-red-700">{error}</p>}{data?.current&&<><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[["Temperature",`${data.current.temperature_2m}°C`],["Humidity",`${data.current.relative_humidity_2m}%`],["Rain now",`${data.current.precipitation} mm`],["Wind",`${data.current.wind_speed_10m} km/h`]].map(([l,x])=><div key={l} className="rounded-2xl bg-[#f5f7f2] p-5"><p className="text-sm text-[#647468]">{l}</p><p className="mt-2 text-2xl font-black">{x}</p></div>)}</div><h2 className="mt-8 text-2xl font-black">7-day forecast</h2><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{data.daily?.time.map((d,i)=><div key={d} className="rounded-2xl border p-4"><p className="font-bold">{new Date(`${d}T00:00:00`).toLocaleDateString("en-GB",{weekday:"short",day:"numeric",month:"short"})}</p><p className="mt-2 text-sm">{data.daily!.temperature_2m_min[i]}–{data.daily!.temperature_2m_max[i]}°C</p><p className="text-sm text-[#647468]">Rain chance {data.daily!.precipitation_probability_max[i]}%</p><p className="text-sm text-[#647468]">Rain {data.daily!.precipitation_sum[i]} mm</p></div>)}</div></>}</section>;
}
