"use client";
import { FormEvent, useMemo, useState } from "react";

type Entry={date:string;crop:string;activity:string;notes:string;cost:string};
const activities=["Planting","Irrigation","Fertilizer","Pest observation","Harvest","Expense","Other"];
export default function FarmDiary(){
 const [crop,setCrop]=useState("Rice"); const [activity,setActivity]=useState("Planting"); const [date,setDate]=useState(""); const [notes,setNotes]=useState(""); const [cost,setCost]=useState(""); const [entries,setEntries]=useState<Entry[]>([]);
 const total=useMemo(()=>entries.reduce((s,e)=>s+(Number(e.cost)||0),0),[entries]);
 function add(e:FormEvent){e.preventDefault();if(!date&&!notes)return;setEntries([{date:date||new Date().toISOString().slice(0,10),crop,activity,notes,cost},...entries]);setNotes("");setCost("");}
 return <section className="mt-8 grid gap-6 lg:grid-cols-[1fr_1.2fr]"><form onSubmit={add} className="rounded-3xl bg-white p-6 shadow-sm"><h2 className="text-xl font-black">Add farm record</h2><div className="mt-5 space-y-4"><label className="block text-sm font-bold">Crop<input value={crop} onChange={e=>setCrop(e.target.value)} className="mt-2 w-full rounded-xl border px-4 py-3 font-normal" placeholder="e.g. Rice"/></label><label className="block text-sm font-bold">Activity<select value={activity} onChange={e=>setActivity(e.target.value)} className="mt-2 w-full rounded-xl border px-4 py-3 font-normal">{activities.map(x=><option key={x}>{x}</option>)}</select></label><label className="block text-sm font-bold">Date<input type="date" value={date} onChange={e=>setDate(e.target.value)} className="mt-2 w-full rounded-xl border px-4 py-3 font-normal"/></label><label className="block text-sm font-bold">Notes<textarea value={notes} onChange={e=>setNotes(e.target.value)} className="mt-2 min-h-28 w-full rounded-xl border px-4 py-3 font-normal" placeholder="What happened in the field?"/></label><label className="block text-sm font-bold">Expense (৳)<input type="number" min="0" value={cost} onChange={e=>setCost(e.target.value)} className="mt-2 w-full rounded-xl border px-4 py-3 font-normal"/></label><button className="w-full rounded-xl bg-[#17351f] px-5 py-3 font-bold text-white">Add record</button></div></form><div className="rounded-3xl bg-[#17351f] p-6 text-white"><div className="flex items-end justify-between"><div><p className="text-sm text-white/60">Farm diary</p><h2 className="text-2xl font-black">Recent records</h2></div><div className="text-right"><p className="text-xs text-white/60">Recorded expenses</p><b>৳{total.toLocaleString()}</b></div></div><div className="mt-6 space-y-3">{entries.length?entries.map((x,i)=><div key={`${x.date}-${i}`} className="rounded-2xl bg-white/10 p-4"><div className="flex flex-wrap justify-between gap-2"><b>{x.crop} · {x.activity}</b><span className="text-sm text-white/60">{x.date}</span></div>{x.notes&&<p className="mt-2 text-sm leading-6 text-white/75">{x.notes}</p>}{Number(x.cost)>0&&<p className="mt-2 text-sm font-bold">Expense: ৳{Number(x.cost).toLocaleString()}</p>}</div>):<p className="rounded-2xl bg-white/10 p-5 text-sm leading-6 text-white/65">No records yet. Add your first field activity.</p>}</div><p className="mt-6 text-xs leading-5 text-white/50">Prototype note: records currently live only in this browser session. Supabase sync can be connected in the next integration step.</p></div></section>;
}
