"use client";
import { useMemo, useState } from "react";

type CropKey = "rice" | "maize" | "wheat" | "vegetables" | "potato";
const crops: Record<CropKey,{label:string; mm:number}> = { rice:{label:"Rice",mm:8}, maize:{label:"Maize",mm:6}, wheat:{label:"Wheat",mm:5}, vegetables:{label:"Vegetables",mm:5}, potato:{label:"Potato",mm:5} };
const methods = [{key:"flood",label:"Surface / flood",eff:0.55},{key:"sprinkler",label:"Sprinkler",eff:0.75},{key:"drip",label:"Drip",eff:0.90}];
export default function IrrigationWaterCalculator(){
 const [crop,setCrop]=useState<CropKey>("rice"); const [area,setArea]=useState("1"); const [method,setMethod]=useState("flood");
 const r=useMemo(()=>{const acres=Math.max(0,Number(area)||0);const fieldM2=acres*4046.8564224;const mm=crops[crop].mm;const eff=methods.find(x=>x.key===method)?.eff||.55;const fieldLiters=fieldM2*mm;const appliedLiters=fieldLiters/eff;return {fieldLiters,appliedLiters,m3:appliedLiters/1000,mm,eff}},[area,crop,method]);
 return <section className="mt-8 grid gap-6 lg:grid-cols-2"><div className="rounded-3xl bg-white p-6 shadow-sm"><h2 className="text-xl font-black">Irrigation inputs</h2><div className="mt-5 space-y-4"><label className="block text-sm font-bold">Crop<select value={crop} onChange={e=>setCrop(e.target.value as CropKey)} className="mt-2 w-full rounded-xl border px-4 py-3 font-normal">{Object.entries(crops).map(([k,x])=><option key={k} value={k}>{x.label}</option>)}</select></label><label className="block text-sm font-bold">Land area (acre)<input type="number" min="0" step="0.01" value={area} onChange={e=>setArea(e.target.value)} className="mt-2 w-full rounded-xl border px-4 py-3 font-normal"/></label><label className="block text-sm font-bold">Irrigation method<select value={method} onChange={e=>setMethod(e.target.value)} className="mt-2 w-full rounded-xl border px-4 py-3 font-normal">{methods.map(x=><option key={x.key} value={x.key}>{x.label}</option>)}</select></label></div></div><div className="rounded-3xl bg-[#17351f] p-6 text-white"><p className="text-sm text-white/70">Estimated applied water</p><p className="mt-3 text-5xl font-black">{r.m3.toFixed(1)} m³</p><p className="mt-4 text-lg font-bold">≈ {Math.round(r.appliedLiters).toLocaleString()} litres</p><div className="mt-6 grid grid-cols-2 gap-3 text-sm"><div className="rounded-2xl bg-white/10 p-4"><span className="text-white/60">Reference demand</span><b className="mt-1 block">{r.mm} mm</b></div><div className="rounded-2xl bg-white/10 p-4"><span className="text-white/60">Efficiency</span><b className="mt-1 block">{Math.round(r.eff*100)}%</b></div></div><p className="mt-6 text-xs leading-5 text-white/60">This is a planning estimate. Actual irrigation should account for rainfall, soil moisture, crop stage and local agronomic guidance.</p></div></section>;
}
