"use client";
import {useEffect,useState} from "react";
import {createClient} from "@supabase/supabase-js";

type Opportunity={id:string;keyword:string;intent:string;opportunity_type:string;search_count:number;result_count:number;status:string;title:string|null;slug:string|null;created_at:string};
export default function Page(){const [rows,setRows]=useState<Opportunity[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [filter,setFilter]=useState("all");
async function load(){setLoading(true);const url=process.env.NEXT_PUBLIC_SUPABASE_URL;const key=process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;if(!url||!key){setError("Supabase environment variables are missing.");setLoading(false);return}const supabase=createClient(url,key);let q=supabase.from("content_opportunities").select("id,keyword,intent,opportunity_type,search_count,result_count,status,title,slug,created_at").order("search_count",{ascending:false});if(filter!=="all")q=q.eq("status",filter);const {data,error}=await q.limit(100);if(error)setError(error.message);else setRows(data??[]);setLoading(false)}
useEffect(()=>{load()},[filter]);async function setStatus(id:string,status:string){const url=process.env.NEXT_PUBLIC_SUPABASE_URL;const key=process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;if(!url||!key)return;const supabase=createClient(url,key);const {error}=await supabase.from("content_opportunities").update({status,reviewed_at:new Date().toISOString()}).eq("id",id);if(error)setError(error.message);else load()}
return <main className="min-h-screen bg-[#f5f7f2] text-[#17351f]"><section className="mx-auto max-w-7xl px-6 py-12"><p className="text-sm font-bold uppercase tracking-[.18em] text-[#b58b28]">AGRIVA Intelligence</p><h1 className="mt-3 text-4xl font-black">Live Content Opportunities</h1><p className="mt-3 max-w-3xl text-[#647468]">Live Supabase view of search-driven article, product and tool opportunities. Approval is required before publication.</p><div className="mt-6 flex flex-wrap gap-2">{["all","open","draft","review","approved","published","rejected"].map(f=><button key={f} onClick={()=>setFilter(f)} className={`rounded-xl px-4 py-2 text-sm font-bold capitalize ${filter===f?"bg-[#17351f] text-white":"bg-white"}`}>{f}</button>)}</div>{error&&<p className="mt-4 rounded-xl bg-red-50 p-4 text-sm text-red-700">{error}</p>}{loading?<p className="mt-8 text-sm text-[#647468]">Loading opportunities…</p>:<section className="mt-4 overflow-hidden rounded-3xl bg-white shadow-sm">{rows.length===0?<p className="p-8 text-sm text-[#647468]">No opportunities found for this filter.</p>:rows.map(r=><article key={r.id} className="border-b p-6 last:border-0"><div className="flex flex-wrap items-start justify-between gap-5"><div><p className="text-xs font-bold uppercase tracking-wider text-[#b58b28]">{r.opportunity_type}</p><h2 className="mt-1 text-xl font-black">{r.title||r.keyword}</h2><p className="mt-1 text-sm text-[#647468]">Keyword: {r.keyword} · Intent: {r.intent} · Searches: {r.search_count} · Results: {r.result_count}</p></div><span className="rounded-full bg-[#eef5ed] px-3 py-1 text-xs font-bold capitalize">{r.status}</span></div><div className="mt-5 flex flex-wrap gap-2">{(r.status==="open"||r.status==="draft")&&<button onClick={()=>setStatus(r.id,"review")} className="rounded-xl bg-[#17351f] px-4 py-2 text-sm font-bold text-white">Send to review</button>}{r.status==="review"&&<><button onClick={()=>setStatus(r.id,"approved")} className="rounded-xl bg-[#17351f] px-4 py-2 text-sm font-bold text-white">Approve</button><button onClick={()=>setStatus(r.id,"rejected")} className="rounded-xl border px-4 py-2 text-sm font-bold">Reject</button></>}{r.status==="approved"&&<button onClick={()=>setStatus(r.id,"published")} className="rounded-xl bg-[#17351f] px-4 py-2 text-sm font-bold text-white">Mark published</button>}</div></article>)}</section>}<div className="mt-6 rounded-2xl border border-dashed p-5 text-sm leading-6 text-[#647468]">Production note: this page controls opportunity workflow only. Article/product generation should create draft records; publishing should require a separate authenticated admin action.</div></section></main>}
