-- AGRIVA production marketplace reconciliation.
create or replace function public.is_admin() returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.profiles where id=auth.uid() and role='admin') $$;

create table if not exists public.reseller_links (id uuid primary key default gen_random_uuid(),reseller_id uuid not null references public.profiles(id) on delete cascade,product_id uuid not null references public.products(id) on delete cascade,code text not null unique,created_at timestamptz not null default now(),expires_at timestamptz not null default (now()+interval '15 days'));
create index if not exists reseller_links_reseller_idx on public.reseller_links(reseller_id,created_at desc);
create index if not exists reseller_links_product_idx on public.reseller_links(product_id);

create table if not exists public.attribution_sessions (id uuid primary key default gen_random_uuid(),reseller_id uuid not null references public.profiles(id) on delete cascade,product_id uuid not null references public.products(id) on delete cascade,code text not null,visitor_token text not null,expires_at timestamptz not null,created_at timestamptz not null default now());
create unique index if not exists attribution_session_token_idx on public.attribution_sessions(code,visitor_token,product_id);
create index if not exists attribution_session_reseller_idx on public.attribution_sessions(reseller_id,created_at desc);

create table if not exists public.marketplace_orders (id uuid primary key default gen_random_uuid(),buyer_id uuid references public.profiles(id) on delete set null,farmer_id uuid not null references public.profiles(id) on delete restrict,reseller_id uuid references public.profiles(id) on delete set null,product_id uuid not null references public.products(id) on delete restrict,quantity integer not null check(quantity>0),unit_price numeric(12,2) not null check(unit_price>=0),delivery_fee numeric(12,2) not null default 0 check(delivery_fee>=0),total_amount numeric(12,2) not null check(total_amount>=0),commission_percent numeric(5,2) not null default 0 check(commission_percent between 0 and 100),commission_amount numeric(12,2) not null default 0 check(commission_amount>=0),attribution_code text,attribution_expires_at timestamptz,payment_method text not null default 'cod' check(payment_method in ('cod','online')),payment_status text not null default 'pending' check(payment_status in ('pending','paid','failed','refunded')),status text not null default 'processing' check(status in ('pending','processing','shipped','delivered','completed','cancelled','refunded')),shipping_address jsonb not null default '{}'::jsonb,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),paid_at timestamptz,shipped_at timestamptz,delivered_at timestamptz);
create index if not exists marketplace_orders_buyer_idx on public.marketplace_orders(buyer_id,created_at desc);
create index if not exists marketplace_orders_farmer_idx on public.marketplace_orders(farmer_id,created_at desc);
create index if not exists marketplace_orders_reseller_idx on public.marketplace_orders(reseller_id,created_at desc);

create table if not exists public.reseller_commissions (id uuid primary key default gen_random_uuid(),reseller_id uuid not null references public.profiles(id) on delete restrict,order_id uuid not null unique references public.marketplace_orders(id) on delete cascade,amount numeric(12,2) not null check(amount>=0),status text not null default 'pending' check(status in ('pending','approved','paid','reversed')),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create index if not exists reseller_commissions_reseller_idx on public.reseller_commissions(reseller_id,created_at desc);

alter table public.reseller_links enable row level security;
alter table public.attribution_sessions enable row level security;
alter table public.marketplace_orders enable row level security;
alter table public.reseller_commissions enable row level security;
create policy if not exists "reseller_links_owner_read" on public.reseller_links for select using(auth.uid()=reseller_id or public.is_admin());
create policy if not exists "attribution_owner_read" on public.attribution_sessions for select using(auth.uid()=reseller_id or public.is_admin());
create policy if not exists "marketplace_orders_parties_read" on public.marketplace_orders for select using(auth.uid()=buyer_id or auth.uid()=farmer_id or auth.uid()=reseller_id or public.is_admin());
create policy if not exists "reseller_commissions_owner_read" on public.reseller_commissions for select using(auth.uid()=reseller_id or public.is_admin());

create or replace function public.create_reseller_link(p_product_id uuid,p_days integer default 15) returns public.reseller_links language plpgsql security definer set search_path=public as $$
declare r public.reseller_links; begin if auth.uid() is null then raise exception 'Authentication required'; end if; if not exists(select 1 from public.profiles where id=auth.uid() and role='reseller') then raise exception 'Reseller role required'; end if; if p_days<1 or p_days>30 then raise exception 'Invalid attribution window'; end if; if not exists(select 1 from public.products where id=p_product_id and status='active') then raise exception 'Product is not active'; end if; insert into public.reseller_links(reseller_id,product_id,code,expires_at) values(auth.uid(),p_product_id,'R-'||upper(substr(encode(gen_random_bytes(8),'hex'),1,10)),now()+make_interval(days=>p_days)) returning * into r; return r; end;$$;
grant execute on function public.create_reseller_link(uuid,integer) to authenticated;

create or replace function public.resolve_reseller_attribution(p_code text,p_visitor_token text,p_product_id uuid) returns table(reseller_id uuid,expires_at timestamptz) language sql security definer set search_path=public as $$ select a.reseller_id,a.expires_at from public.attribution_sessions a where a.code=p_code and a.visitor_token=p_visitor_token and a.product_id=p_product_id and a.expires_at>now() order by a.created_at desc limit 1; $$;
grant execute on function public.resolve_reseller_attribution(text,text,uuid) to anon,authenticated;

create or replace function public.finalize_marketplace_cod_order(p_product_id uuid,p_quantity integer,p_shipping_address jsonb,p_reseller_id uuid default null,p_attribution_code text default null,p_attribution_expires_at timestamptz default null) returns public.marketplace_orders language plpgsql security definer set search_path=public as $$
declare uid uuid; p public.products; o public.marketplace_orders; total numeric; commission numeric; rate numeric; begin uid:=auth.uid(); if uid is null then raise exception 'Authentication required'; end if; if p_quantity<1 then raise exception 'Invalid quantity'; end if; select * into p from public.products where id=p_product_id and status='active' for update; if not found then raise exception 'Product unavailable'; end if; if p.stock<p_quantity then raise exception 'Insufficient stock'; end if; rate:=case when p_reseller_id is null then 0 else coalesce(p.reseller_commission_percent,0) end; total:=round(p.price*p_quantity,2); commission:=round(total*rate/100,2); insert into public.marketplace_orders(buyer_id,farmer_id,reseller_id,product_id,quantity,unit_price,total_amount,commission_percent,commission_amount,attribution_code,attribution_expires_at,payment_method,payment_status,status,shipping_address) values(uid,p.farmer_id,p_reseller_id,p.id,p_quantity,p.price,total,rate,commission,p_attribution_code,p_attribution_expires_at,'cod','pending','processing',p_shipping_address) returning * into o; update public.products set stock=stock-p_quantity,updated_at=now() where id=p.id; if p_reseller_id is not null then insert into public.reseller_commissions(reseller_id,order_id,amount,status) values(p_reseller_id,o.id,commission,'pending'); end if; return o; end;$$;
grant execute on function public.finalize_marketplace_cod_order(uuid,integer,jsonb,uuid,text,timestamptz) to authenticated;

create or replace function public.set_marketplace_order_status(p_order_id uuid,p_status text) returns public.marketplace_orders language plpgsql security definer set search_path=public as $$
declare uid uuid; o public.marketplace_orders; old_status text; begin uid:=auth.uid(); if uid is null then raise exception 'Authentication required'; end if; select * into o from public.marketplace_orders where id=p_order_id for update; if not found then raise exception 'Order not found'; end if; if not (public.is_admin() or o.farmer_id=uid) then raise exception 'Not authorized'; end if; old_status:=o.status; if p_status not in ('processing','shipped','delivered','completed','cancelled','refunded') then raise exception 'Invalid order status'; end if; if old_status in ('cancelled','refunded') then raise exception 'Order is already closed'; end if; if p_status in ('cancelled','refunded') and old_status not in ('cancelled','refunded') then update public.products set stock=stock+o.quantity,updated_at=now() where id=o.product_id; update public.reseller_commissions set status='reversed',updated_at=now() where order_id=o.id and status in ('pending','approved'); end if; update public.marketplace_orders set status=p_status,updated_at=now(),shipped_at=case when p_status='shipped' then coalesce(shipped_at,now()) else shipped_at end,delivered_at=case when p_status in ('delivered','completed') then coalesce(delivered_at,now()) else delivered_at end where id=o.id returning * into o; return o; end;$$;
grant execute on function public.set_marketplace_order_status(uuid,text) to authenticated;

create or replace function public.request_commission_payout(p_amount numeric,p_method text) returns public.commission_payouts language plpgsql security definer set search_path=public as $$
declare p public.commission_payouts; uid uuid; available numeric; begin uid:=auth.uid(); if uid is null then raise exception 'Authentication required'; end if; select coalesce(sum(amount),0) into available from public.reseller_commissions where reseller_id=uid and status='approved'; if p_amount<=0 or p_amount>available then raise exception 'Requested amount exceeds approved commission balance'; end if; insert into public.commission_payouts(reseller_id,amount,payment_method) values(uid,p_amount,p_method) returning * into p; return p; end;$$;
grant execute on function public.request_commission_payout(numeric,text) to authenticated;
